# Generated by Django 3.2.15 on 2023-06-17 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='document',
            field=models.FileField(blank=True, upload_to='REPORT/documents/uploads/24', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
