# Generated by Django 3.2.15 on 2023-06-19 20:12

import django.core.validators
from django.db import migrations, models
import weeklyreport.models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0006_alter_reports_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='document',
            field=models.FileField(blank=True, upload_to='REPORT/documents/uploads/2023/25', validators=[weeklyreport.models.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
