# Generated by Django 3.2.15 on 2023-07-24 13:32

import django.core.validators
from django.db import migrations, models
import weeklyreport.models


class Migration(migrations.Migration):

    dependencies = [
        ('weeklyreport', '0008_alter_reports_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='unithead_mail',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='reports',
            name='document',
            field=models.FileField(blank=True, upload_to='REPORT/documents/uploads/2023/30', validators=[weeklyreport.models.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'])]),
        ),
    ]
