# Generated by Django 3.2.15 on 2022-11-03 15:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.PositiveIntegerField(default=0, verbose_name='Service ID')),
                ('servicename', models.CharField(default='', max_length=100, verbose_name='Servis adı')),
                ('teamname', models.CharField(default='', editable=False, max_length=100, verbose_name='Ekip adı')),
                ('sre', models.CharField(max_length=100, verbose_name='SRE')),
                ('srebackup', models.CharField(max_length=100, verbose_name='SRE Yedek')),
                ('vendor', models.CharField(default='', help_text="GT ya da 'Firma adı' giriniz ", max_length=100, verbose_name='Vendor')),
                ('serverlocation', multiselectfield.db.fields.MultiSelectField(choices=[('Intranet', 'Intranet'), ('Extranet', 'Extranet'), ('Internet', 'Internet')], help_text='Çoklu seçim yapabilirsiniz', max_length=100, verbose_name='Sunucu lokasyonu')),
                ('nonprodenvtypes', multiselectfield.db.fields.MultiSelectField(choices=[('Dev', 'Dev'), ('Test', 'Test'), ('QA', 'QA'), ('Yok', 'Yok')], help_text='Çoklu seçim yapabilirsiniz', max_length=15, verbose_name='Production dışında hangi ortamlar var?')),
                ('servertype', multiselectfield.db.fields.MultiSelectField(choices=[('Fiziksel', 'Fiziksel'), ('Sanal', 'Sanal')], help_text='Çok seçim yapabilirsiniz', max_length=100, verbose_name='Sunucu tipi')),
                ('ostype', multiselectfield.db.fields.MultiSelectField(choices=[('Windows Server 2008', 'Windows Server 2008'), ('Windows Server 2012', 'Windows Server 2012'), ('Windows Server 2016', 'Windows Server 2016'), ('Windows Server 2019', 'Windows Server 2019'), ('Windows Server 2022', 'Windows Server 2022'), ('Linux RedHat 5', 'Linux RedHat 5'), ('Linux RedHat 6', 'Linux RedHat 6'), ('Linux RedHat 7', 'Linux RedHat 7'), ('Linux RedHat 8', 'Linux RedHat 8'), ('Linux Debian', 'Linux Debian'), ('Linux CenOS', 'Linux CenOS'), ('Linux Suse', 'Linux Suse'), ('Linux Ubuntu', 'Linux Ubuntu'), ('Mainframe', 'Mainframe'), ('Unix', 'Unix')], help_text='Çoklu seçim yapabilirsiniz', max_length=100, verbose_name='İşletim sistemi tipi')),
                ('appservercount', models.PositiveIntegerField(default=0, verbose_name='Uygulama sunucu sayısı')),
                ('serverhostnames', models.CharField(default='', max_length=300, verbose_name='Sunucu bilgileri')),
                ('dbtype', multiselectfield.db.fields.MultiSelectField(choices=[('Oracle', 'Oracle'), ('MySQL', 'MySQL'), ('Microsoft SQL Server', 'Microsoft SQL Server'), ('DB2', 'DB2'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB'), ('Redis', 'Redis'), ('Elasticsearch', 'Elasticsearch'), ('SQLite', 'SQLite'), ('Cassandra', 'Cassandra'), ('MariaDB', 'MariaDB'), ('Hive', 'Hive'), ('Couchbase', 'Couchbase'), ('InFluxDB', 'InFluxDB'), ('Veritabanı yok', 'Veritabanı yok')], help_text='Çoklu seçim yapabilirsiniz', max_length=100, verbose_name='Veritabanı tipi')),
                ('dbconnstring', models.CharField(default='', max_length=300, verbose_name='Veritabanı bağlantı bilgisi')),
                ('monitoringapps', multiselectfield.db.fields.MultiSelectField(choices=[('Dynatrace', 'Dynatrace'), ('SLM', 'SLM'), ('Microsoft SCOM', 'Microsoft SCOM'), ('Sitescope', 'Sitescope'), ('Prometheus', 'Prometheus'), ('DbVision', 'DbVision'), ('BPM', 'BPM'), ('AIOPS', 'AIOPS'), ('Monitor edilmiyor', 'Monitor edilmiyor')], help_text='Çoklu seçim yapabilirsiniz', max_length=86, verbose_name='Hangi uygulamalar ile monitor ediliyor?')),
                ('logintegration', multiselectfield.db.fields.MultiSelectField(choices=[('Splunk', 'Splunk'), ('ELK', 'ELK'), ('Prometheus', 'Prometheus'), ('ArcSight', 'ArcSight'), ('Log entegrasyonu yok', 'Log entegrasyonu yok')], help_text='Çoklu seçim yapabilirsiniz. Sunucu üstündeki loglar yok olarak değerlendirilmelidir', max_length=51, verbose_name='Log entegrasyonu var mı?')),
                ('logindex', models.CharField(blank=True, default='', max_length=300, verbose_name='Log index bilgisi nedir?')),
                ('supportdetail', multiselectfield.db.fields.MultiSelectField(choices=[('SLA - Var', 'SLA - Var'), ('SLA - Yok', 'SLA - Yok'), ('Support - 24x7', 'Support - 24x7'), ('Support - 8x5', 'Support - 8x5'), ('Support Yok', 'Support Yok'), ('Bilmiyorum', 'Bilmiyorum')], help_text='Çoklu seçim yapabilirsiniz', max_length=100, verbose_name='Support detayları')),
                ('integratedservices', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LDAP', 'LDAP'), ('AD', 'AD'), ('ODI', 'ODI'), ('SSO', 'SSO'), ('IVR', 'IVR'), ('Smart', 'Smart'), ('Coolgen', 'Coolgen'), ('ARK', 'ARK'), ('DWH(Raporlama)', 'DWH(Raporlama)'), ('STEP', 'STEP'), ('Ödeme Sistemleri', 'Ödeme Sistemleri'), ('Diğer', 'Diğer')], help_text='Çoklu seçim yapabilirsiniz', max_length=80, verbose_name='Entegre olduğu uygulamalar/servisler')),
                ('other', models.CharField(blank=True, default='', max_length=100, verbose_name='Diğerleri (Eğer yukarıdaki seçeneklerin dışında bir entegrasyon varsa burada belirtiniz)')),
                ('sox', models.BooleanField(default=False, verbose_name='SOX kritik mi?')),
                ('soxcriticdata', models.BooleanField(default=False, verbose_name='Müşteri kritik veri barındırır mı? (Örneğin; işlem detayı, adres bilgisi vs)')),
                ('odmplatform', models.BooleanField(default=False, verbose_name='ODM platformu var mı?')),
                ('highavailability', models.BooleanField(default=False, verbose_name='Kendi içinde yedeklilik (HA) var mı?')),
                ('regulatoryintegration', models.BooleanField(default=False, verbose_name='Dış kurum entegrasyonu var mı?')),
                ('customereffect', models.BooleanField(default=False, verbose_name='Servis kesintisi iç/dış müşteriyi etkiler mi?')),
                ('backup', models.BooleanField(default=False, verbose_name="Uygulama sunucularının backup'ı var mı?")),
            ],
        ),
    ]
