# Generated by Django 3.2.15 on 2023-06-17 14:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='integratedservices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('LDAP', 'LDAP'), ('AD', 'AD'), ('ODI', 'ODI'), ('SSO', 'SSO'), ('IVR', 'IVR'), ('Smart', 'Smart'), ('CyberArk', 'CyberArk'), ('Coolgen', 'Coolgen'), ('ARK', 'ARK'), ('DWH(Raporlama)', 'DWH(Raporlama)'), ('STEP', 'STEP'), ('Ödeme Sistemleri', 'Ödeme Sistemleri'), ('Diğer', 'Diğer')], help_text='Çoklu seçim yapabilirsiniz', max_length=89, verbose_name='Entegre olduğu uygulamalar/servisler'),
        ),
    ]
