# Generated by Django 3.2.15 on 2022-09-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='teamname',
            field=models.CharField(default=' ', max_length=100, verbose_name='Ekip adı'),
        ),
    ]
